### ISSUE TITLE
Get error when tried to run (windows 10)

### ISSUE THREAD

**Issue by RobinHooD1024** [krypdkat/AmoveoMinerMan#4]
Get an error when trying to start on my windows 10. VC++ 2010 installed. Maybe there's any additional required software ?

**Comment by krypdkat** [comment]
We've compiled this miner on VS 2015, anw, let's try new version

**Comment by RobinHooD1024** [comment]
Still very often got an error. By the way, how to see hashrate in new version ?

**Comment by RobinHooD1024** [comment]
tried new 0.2.2 version and still got errors. 
![image](https://user-images.githubusercontent.com/36574947/39971163-d383ac60-56c4-11e8-992a-ce8794318dd1.png)
Maybe you have any config value for 1080ti, so I can just put it in deviceconfig ?

**Comment by RobinHooD1024** [comment]
also have this type of errors
http://prntscr.com/jhgtmt

**Comment by krypdkat** [comment]
solved!
