### ISSUE TITLE
multigpu??

### ISSUE THREAD

**Issue by Twente-Mining** [krypdkat/AmoveoMinerMan#6]
i'm not getting it running on multiple gpu.
please explain how to get that done

**Comment by krypdkat** [comment]
you just run cmd.exe, then run AmoveoMinerMan.exe. It will configure things automatically and ask you to restart the app. Run  AmoveoMinerMan.exe again, the miner auto start on multigpus:
this is what you will see after 1 minute:
![image](https://user-images.githubusercontent.com/39078779/39959095-d57ddbdc-5636-11e8-9fdd-2aaf877a99a0.png)

**Comment by aklakl1** [comment]
Actually miner uses only 0 and 1 GPUs, try it on 3 rigs with 3, 6 and 8 GPUs.

**Comment by rheza** [comment]
yeah, the miner never start any work on gpu

**Comment by aklakl1** [comment]
Hmm, the problem was: for some reason autotune for 0 and 1 GPU was good, but for the rest of cards it was 0 0 params.

**Comment by krypdkat** [comment]
solved!
